export const SITE = {
  name: 'Hirael',
  description: 'Components, blocks and templates for shadcn/ui, built on Radix UI and Base UI.',
  tagline: 'Components, blocks and templates for shadcn/ui',
  longDescription:
    'A collection of shadcn/ui components, blocks and page templates built on Radix UI and Base UI. Multi-select, date pickers, file dropzone and more, installed with the shadcn CLI and any preset, in light, dark and RTL.',
  url: 'https://hirael.com',
  version: '0.1',
  author: 'Mohammad Shehadeh',
  authorUrl: 'https://mohammadshehadeh.com',
  githubUrl: 'https://github.com/mohammadshehadeh/',
  githubRepoUrl: 'https://github.com/MohammadShehadeh/hirael',
  keywords: [
    'shadcn',
    'shadcn ui',
    'shadcn registry',
    'shadcn components',
    'shadcn blocks',
    'shadcn templates',
    'radix ui',
    'base ui',
    'react components',
    'ui library',
    'tailwind css',
    'multi-select',
    'combobox',
    'date picker',
    'file dropzone',
    'next.js components',
    'next.js templates',
    'react templates',
    'hirael',
    'react 19',
  ],
  registry: {
    name: 'hirael',
    origin: 'https://hirael.com',
  },
} as const;

export const NAV_LINKS: { href: string; label: string; isExternal?: boolean }[] = [
  { href: '/components', label: 'Components' },
  { href: '/blocks', label: 'Blocks' },
  { href: '/templates', label: 'Templates' },
  { href: '/changelog', label: 'Changelog' },
];
